//Declaracion de valor en Js moderno
// let numero = 5;
// numero = 8
// const dir = 4;



//Alert JS
// alert("CIRNO GANG");
// console.log("This is a test printed in the HTML document");
// console.log(numero);
// console.log(dir);

//Concatenación
let nombre= "Roberto";
let Apellido= "López";
console.log("Mi nombre es"+nombre+ "",Apellido);
document.write("im fine")
let Text = document.querySelector("#text")

Text.innerHTML= `<h3>CIRNO GANG</h3>`;

console.log(Text);